### ISSUE TITLE
 Implement Notification System in your Chat App

### ISSUE THREAD

**Issue by shahzadhaider1** [Hammad887/chatapp#18]
The next task for you is the implementation of a notification system:
- This would notify all users whenever new messages are posted in chatrooms they are a part of. 
- This could be through real-time WebSocket notifications, polling, or any other suitable method. 
- We can also allow users to set their notification preferences, such as choosing to receive notifications for all messages, mentions, or messages in specific chatrooms.
- Ensure that the notification system integrates seamlessly with the existing chat app microservice.
- Make any necessary updates to the database layer to handle notification-related data efficiently.
- Prioritize efficiency in your implementation to minimize server load and optimize real-time notifications.
- Write unit tests to validate the functionality of the notification system
- Update the Swagger API documentation to include information about any new endpoints related to chatroom notifications (if required).

We believe that successfully implementing this notification system will not only enhance the chat app's functionality but also provide you with valuable experience and greatly enhance your coding skills. 

Important: Please refrain from seeking assistance from ChatGPT for every issue. Instead, utilize it only when you encounter exceptionally challenging problems. If you do seek help, ensure that you thoroughly understand the information you are obtaining rather than simply copying it.

If you have any questions or need further assistance during this task, please don't hesitate to reach out. Good luck, and we look forward to seeing your work!

**Comment by Hammad887** [comment]
PR opened for this issue.
